[platform-api] Fix failure of determine-reboot-cause.service.
The issue is caused by the wrong type of value returned from the "get_reboot_cause" function.

$ systemctl list-units --failed
  UNIT                           LOAD   ACTIVE SUB    DESCRIPTION
_ determine-reboot-cause.service loaded failed failed Reboot cause determination service

$ /usr/local/bin/determine-reboot-cause
Traceback (most recent call last):
  File "/usr/local/bin/determine-reboot-cause", line 262, in <module>
    main()
  File "/usr/local/bin/determine-reboot-cause", line 225, in main
    previous_reboot_cause, additional_reboot_info = determine_reboot_cause()
  File "/usr/local/bin/determine-reboot-cause", line 176, in determine_reboot_cause
    hardware_reboot_cause = find_hardware_reboot_cause()
  File "/usr/local/bin/determine-reboot-cause", line 129, in find_hardware_reboot_cause
    hardware_reboot_cause = hardware_reboot_cause_major + hardware_reboot_cause_minor_str
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'